### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by daegontaven** [DiscordFederation/Erin#20]
This is not related to #8. Some simple tests can be added to de-coupled methods and functions.

**Task list**:
- [x] Verify `glia init` retrieves proper files
- [x] Ensure [`glia.cli`](https://github.com/DiscordFederation/Glia/tree/124eca51f8dc8485b17411a2c33ebf58e51339a3/glia/cli) commands work
- [x] Test [`glia.core.utils`](https://github.com/DiscordFederation/Glia/blob/124eca51f8dc8485b17411a2c33ebf58e51339a3/glia/core/utils.py)
